#low bin version
python lscan.py -f bin/bin-libz-1.2.3 -s sig/libz-1.2.3.sig
python lscan.py -f bin/bin-libz-1.2.3 -s sig/libz-1.2.7.sig
python lscan.py -f bin/bin-libz-1.2.3 -s sig/libz-1.2.8.sig
python lscan.py -f bin/bin-glib2-2.40 -s sig/libglib2-2.40.sig
python lscan.py -f bin/bin-glib2-2.40 -s sig/libglib2-2.44.sig
python lscan.py -f bin/bin-glib2-2.40 -s sig/libglib2-2.46.sig
python lscan.py -f bin/bin-libssl-1.0.1e -s sig/libssl-1.0.1e.sig
python lscan.py -f bin/bin-libssl-1.0.1e -s sig/libssl-1.0.2h.sig
python lscan.py -f bin/bin-libxml2-2.9.1 -s sig/libxml2-2.9.1.sig
python lscan.py -f bin/bin-libxml2-2.9.1 -s sig/libxml2-2.9.2.sig
python lscan.py -f bin/bin-libxml2-2.9.1 -s sig/libxml2-2.9.3.sig
python lscan.py -f bin/bin-libstdc++-4.8.1 -s sig/libstdc++-4.8.1.sig
python lscan.py -f bin/bin-libstdc++-4.8.1 -s sig/libstdc++-4.9.1.sig
python lscan.py -f bin/bin-libpthread-2.12 -s sig/libpthread-2.12.sig
python lscan.py -f bin/bin-libpthread-2.12 -s sig/libpthread-2.17.sig
python lscan.py -f bin/bin-libpthread-2.12 -s sig/libpthread-2.22.sig
python lscan.py -f bin/bin-libpthread-2.12 -s sig/libpthread-2.23.sig
python lscan.py -f bin/bin-libm-2.12 -s sig/libm-2.12.sig
python lscan.py -f bin/bin-libm-2.12 -s sig/libm-2.17.sig
python lscan.py -f bin/bin-libm-2.12 -s sig/libm-2.22.sig
python lscan.py -f bin/bin-libm-2.12 -s sig/libm-2.23.sig
python lscan.py -f bin/bin-libpcre-8.30 -s sig/libpcre-8.30.sig
python lscan.py -f bin/bin-libpcre-8.30 -s sig/libpcre-8.37.sig
python lscan.py -f bin/bin-libpcre-8.30 -s sig/libpcre-8.38.sig
python lscan.py -f bin/bin-libcrypto-0.9.8e -s sig/libcrypto-0.9.8e.sig
python lscan.py -f bin/bin-libcrypto-0.9.8e -s sig/libcrypto-1.0.1e.sig
python lscan.py -f bin/bin-libcrypto-0.9.8e -s sig/libcrypto-1.0.2h.sig
#mid bin version
python lscan.py -f bin/bin-libz-1.2.7 -s sig/libz-1.2.3.sig
python lscan.py -f bin/bin-libz-1.2.7 -s sig/libz-1.2.7.sig
python lscan.py -f bin/bin-libz-1.2.7 -s sig/libz-1.2.8.sig
python lscan.py -f bin/bin-glib2-2.44 -s sig/libglib2-2.40.sig
python lscan.py -f bin/bin-glib2-2.44 -s sig/libglib2-2.44.sig
python lscan.py -f bin/bin-glib2-2.44 -s sig/libglib2-2.46.sig
python lscan.py -f bin/bin-libssl-1.0.2h -s sig/libssl-1.0.1e.sig
python lscan.py -f bin/bin-libssl-1.0.2h -s sig/libssl-1.0.2h.sig
python lscan.py -f bin/bin-libxml2-2.9.2 -s sig/libxml2-2.9.1.sig
python lscan.py -f bin/bin-libxml2-2.9.2 -s sig/libxml2-2.9.2.sig
python lscan.py -f bin/bin-libxml2-2.9.2 -s sig/libxml2-2.9.3.sig
python lscan.py -f bin/bin-libstdc++-4.9.1 -s sig/libstdc++-4.8.1.sig
python lscan.py -f bin/bin-libstdc++-4.9.1 -s sig/libstdc++-4.9.1.sig
python lscan.py -f bin/bin-libpthread-2.17 -s sig/libpthread-2.12.sig
python lscan.py -f bin/bin-libpthread-2.17 -s sig/libpthread-2.17.sig
python lscan.py -f bin/bin-libpthread-2.17 -s sig/libpthread-2.22.sig
python lscan.py -f bin/bin-libpthread-2.17 -s sig/libpthread-2.23.sig
python lscan.py -f bin/bin-libm-2.17 -s sig/libm-2.12.sig
python lscan.py -f bin/bin-libm-2.17 -s sig/libm-2.17.sig
python lscan.py -f bin/bin-libm-2.17 -s sig/libm-2.22.sig
python lscan.py -f bin/bin-libm-2.17 -s sig/libm-2.23.sig
python lscan.py -f bin/bin-libpcre-8.37 -s sig/libpcre-8.30.sig
python lscan.py -f bin/bin-libpcre-8.37 -s sig/libpcre-8.37.sig
python lscan.py -f bin/bin-libpcre-8.37 -s sig/libpcre-8.38.sig
python lscan.py -f bin/bin-libcrypto-1.0.1e -s sig/libcrypto-0.9.8e.sig
python lscan.py -f bin/bin-libcrypto-1.0.1e -s sig/libcrypto-1.0.1e.sig
python lscan.py -f bin/bin-libcrypto-1.0.1e -s sig/libcrypto-1.0.2h.sig
#hig bin version
python lscan.py -f bin/bin-libz-1.2.8 -s sig/libz-1.2.3.sig
python lscan.py -f bin/bin-libz-1.2.8 -s sig/libz-1.2.7.sig
python lscan.py -f bin/bin-libz-1.2.8 -s sig/libz-1.2.8.sig
python lscan.py -f bin/bin-glib2-2.46 -s sig/libglib2-2.40.sig
python lscan.py -f bin/bin-glib2-2.46 -s sig/libglib2-2.44.sig
python lscan.py -f bin/bin-glib2-2.46 -s sig/libglib2-2.46.sig
python lscan.py -f bin/bin-libssl-1.0.2h -s sig/libssl-1.0.1e.sig
python lscan.py -f bin/bin-libssl-1.0.2h -s sig/libssl-1.0.2h.sig
python lscan.py -f bin/bin-libxml2-2.9.3 -s sig/libxml2-2.9.1.sig
python lscan.py -f bin/bin-libxml2-2.9.3 -s sig/libxml2-2.9.2.sig
python lscan.py -f bin/bin-libxml2-2.9.3 -s sig/libxml2-2.9.3.sig
python lscan.py -f bin/bin-libstdc++-4.9.1 -s sig/libstdc++-4.8.1.sig
python lscan.py -f bin/bin-libstdc++-4.9.1 -s sig/libstdc++-4.9.1.sig
python lscan.py -f bin/bin-libpthread-2.23 -s sig/libpthread-2.12.sig
python lscan.py -f bin/bin-libpthread-2.23 -s sig/libpthread-2.17.sig
python lscan.py -f bin/bin-libpthread-2.23 -s sig/libpthread-2.22.sig
python lscan.py -f bin/bin-libpthread-2.23 -s sig/libpthread-2.23.sig
python lscan.py -f bin/bin-libm-2.22 -s sig/libm-2.12.sig
python lscan.py -f bin/bin-libm-2.22 -s sig/libm-2.17.sig
python lscan.py -f bin/bin-libm-2.22 -s sig/libm-2.22.sig
python lscan.py -f bin/bin-libm-2.22 -s sig/libm-2.23.sig
python lscan.py -f bin/bin-libpcre-8.38 -s sig/libpcre-8.30.sig
python lscan.py -f bin/bin-libpcre-8.38 -s sig/libpcre-8.37.sig
python lscan.py -f bin/bin-libpcre-8.38 -s sig/libpcre-8.38.sig
python lscan.py -f bin/bin-libcrypto-1.0.2h -s sig/libcrypto-0.9.8e.sig
python lscan.py -f bin/bin-libcrypto-1.0.2h -s sig/libcrypto-1.0.1e.sig
python lscan.py -f bin/bin-libcrypto-1.0.2h -s sig/libcrypto-1.0.2h.sig
